work_dir: outputs/train/fs26/v220--satudora_veo3_awlrecord--split-14-class--nodistinct--2s-15frames--v2--b
phase: train

# feeder
feeder: feeders.feeder_from_protogcn_format.Feeder
train_feeder_args:
  data_path: /home/laptq/ProtoGCN/outputs/convert_pkl_STGCN_to_ProtoGCN/fs26/satudora_veo3_awlrecord--split-14-class--nodistinct--2s-15frames--v2/train.pkl
  split: train
  layout: coco_headless
  aug_method: "123"
  intra_p: 0.5
  inter_p: 0.0
  partition: True
  class_map: null
  ske_feat: "b"
  debug: False

test_feeder_args:
  data_path: /home/laptq/ProtoGCN/outputs/convert_pkl_STGCN_to_ProtoGCN/fs26/shoplift25min_satudoraR9--split-14-class--nodistinct--2s-15frames/val.pkl
  split: val
  layout: coco_headless
  partition: True
  class_map: null #[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
  ske_feat: "b"
  eval_metrics: "harmonic_mean_recall"    # acc harmonic_mean_recall
  class_weights: [1, 1, 1, 1, 1, 1, 1, 1.5, 1.5, 1.5, 1.5, 2.0, 2.0, 2.0]

# model
model: model.SkateFormer.SkateFormer_
model_args:
  in_channels: 2
  num_classes: 14
  num_people: 1
  num_points: 12
  kernel_size: 7
  num_heads: 32
  attn_drop: 0.5
  head_drop: 0.0
  rel: True
  drop_path: 0.2
  type_1_size: [4, 3]
  type_2_size: [4, 4]
  type_3_size: [4, 3]
  type_4_size: [4, 4]
  mlp_ratio: 4.0
  index_t: True

#optim
optimizer: AdamW
weight_decay: 0.1
lr_scheduler: cosine
base_lr: 1e-3
min_lr: 1e-5
warmup_lr: 1e-7
warmup_prefix: False
warm_up_epoch: 3

# training
device: [0]
batch_size: 128
test_batch_size: 1024
num_epoch: 60
nesterov: True
grad_clip: True
grad_max: 1.0
loss_type: LSCE
